import { Inter } from "next/font/google";
import "./globals.css";
import "./style.css";
import Navbar from "./components/Layout/Navbar";
import Footer from "./components/Layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} cryww cs22w cyksu cfglz chz9p`}>

          <div className="ciknu c4xpn crvnt clzjs c84kl">
            <Navbar/>
              <main className="cxgft">
                {children}
              </main>
            <Footer/>
          </div>


       
      </body>
    </html>
  );
}
